# Generated by Django 3.1.6 on 2021-02-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('number', models.CharField(max_length=10, verbose_name='Номер договора')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Даза заключения договора')),
                ('end_date', models.DateField(verbose_name='Даза окончания договора')),
                ('tel1', models.CharField(max_length=12, verbose_name='Телефон 1')),
                ('tel2', models.CharField(max_length=12, verbose_name='Телефон 2')),
                ('tel3', models.CharField(max_length=12, verbose_name='Телефон 3')),
                ('fiz', models.BooleanField(verbose_name='Физлицо')),
                ('address_city', models.CharField(max_length=100, verbose_name='Населенный пункт')),
                ('address_street', models.CharField(max_length=200, verbose_name='Улица')),
                ('address_house', models.CharField(max_length=20, verbose_name='Дом')),
                ('address_kv', models.IntegerField(verbose_name='Квартира')),
                ('equip', models.CharField(max_length=100, verbose_name='Оборудование')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('discount', models.IntegerField(verbose_name='Скидка')),
                ('amount', models.IntegerField(verbose_name='Итого')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
            },
        ),
    ]
