# Generated by Django 3.1.6 on 2021-02-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='tel1',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон 1'),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='tel2',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон 2'),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='tel3',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон 3'),
        ),
    ]
