# Generated by Django 3.1.6 on 2021-02-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogovor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='active',
            field=models.BooleanField(default=1, verbose_name='Действующий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='address_kv',
            field=models.CharField(blank=True, max_length=10, verbose_name='Квартира'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.BooleanField(verbose_name='Наличные')),
                ('date', models.DateField(verbose_name='Даза оплаты')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('pay_place', models.CharField(blank=True, max_length=10, verbose_name='Место оплаты')),
                ('dogovor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogovor.dogovor')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
