# Generated by Django 3.1.6 on 2021-02-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovor', '0002_auto_20210218_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_place',
            field=models.CharField(blank=True, choices=[('В офисе', 'В офисе'), ('обходчику', 'обходчику'), ('на р/счет', 'на р/счет')], default='В офисе', max_length=10, verbose_name='Место оплаты'),
        ),
    ]
