# Generated by Django 3.1.7 on 2021-04-01 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dogovor', '0004_auto_20210331_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='time',
        ),
        migrations.AddField(
            model_name='notification',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания уведомления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='send_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправки уведомления'),
        ),
    ]
