# Generated by Django 3.1.7 on 2021-04-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovor', '0005_auto_20210401_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='ФИО')),
                ('func', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tel',
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('Viber', 'Viber'), ('Telegram', 'Telegram'), ('Call', 'Call')], default='SMS', max_length=10, verbose_name='Тип уведомления'),
        ),
    ]
