# Generated by Django 3.1.7 on 2021-04-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogovor', '0006_auto_20210407_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='send_time',
            new_name='send_time_1',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='success',
            new_name='success_1',
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_time_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправки уведомления'),
        ),
        migrations.AddField(
            model_name='notification',
            name='success_2',
            field=models.BooleanField(default=False, verbose_name='Успешно'),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='date',
            field=models.DateField(blank=True, verbose_name='Дата заключения договора'),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания договора'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_place',
            field=models.CharField(blank=True, default='В офисе', max_length=50, verbose_name='Место оплаты'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('address_city', models.CharField(max_length=300, verbose_name='Адрес')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('job', models.CharField(max_length=200, verbose_name='Работы')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Итого')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Примечание')),
                ('completed', models.BooleanField(verbose_name='Выполнен')),
                ('dogovor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dogovor.dogovor')),
            ],
        ),
    ]
