# Generated by Django 3.1.7 on 2021-04-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogovor', '0007_auto_20210414_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Наряд', 'verbose_name_plural': 'Наряды'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_city',
            new_name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dogovor.worker'),
        ),
    ]
