# Generated by Django 3.1.6 on 2021-04-24 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogovor', '0008_auto_20210414_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Телефон'),
        ),
    ]
