# Generated by Django 3.1.6 on 2021-04-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovor', '0011_auto_20210424_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogovor',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления договора'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время обновления платежа'),
        ),
    ]
