# Generated by Django 3.1.7 on 2021-04-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovor', '0015_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='terminate_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата расторжения договора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Выполнен'),
        ),
    ]
