# Generated by Django 3.2 on 2021-05-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovor', '0016_auto_20210428_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='dolg',
            field=models.BooleanField(default=False, verbose_name='Долг'),
        ),
    ]
