# Generated by Django 3.2 on 2021-05-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogovor', '0017_payment_dolg'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set(),
        ),
    ]
