# Generated by Django 3.1.7 on 2021-05-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovor', '0018_alter_plan_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='counter',
            field=models.BooleanField(default=False, verbose_name='Счетчик'),
        ),
        migrations.AddField(
            model_name='order',
            name='page',
            field=models.IntegerField(default=1, verbose_name='Страница'),
        ),
    ]
